/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoAhorcados;

/**
 *
 * @author Andrei
 */
public class v5StartGame extends javax.swing.JFrame {

    /**
     * Creates new form v5StartGame
     */
    boolean debug;
    String nombre;
    int level;
    public static int theme;
    int attempts;
    int totalAttempts;
    String secretWordHiddenbr;
    String secretWordbr;
    String lettersPut = "";
    int lettersNumber = 0;
    classes caller = new classes();
    public v5StartGame() {
        initComponents();
    }
    public v5StartGame(boolean debugger, String nombrebr, int levelbr, int themebr) {
        initComponents();
        this.debug = debugger;
        this.nombre = nombrebr;
        this.level = levelbr;
        this.theme = themebr;
        this.attempts = 1;
        jLabel3.setText("¡Gracias por jugar, " + nombre + "!");
        switch(levelbr)
        {
            case 1:
            this.totalAttempts = 5;
            break;
            case 2:
            this.totalAttempts = 3;
            break;
            case 3:
            this.totalAttempts = 2;
            break;
            case 4:
            this.totalAttempts = 2;
            break;
            default: 
            this.totalAttempts = 5;
        }
        
        classes caller = new classes();
        caller.generarPalabra(v5StartGame.theme);
        this.secretWordbr = caller.secretWord;
        this.secretWordHiddenbr = caller.secretWordHidden;
        if(debug)
        {
            System.out.println("Tema: " + v5StartGame.theme);
            System.out.println("Palabra secreta: " + this.secretWordbr);
            System.out.println("Palabra Oculta: " + this.secretWordHiddenbr);
        }
        this.lettersNumber = this.secretWordbr.length();
        jTextField1.setText("Intento " + this.attempts + " de " + this.totalAttempts + " (" + lettersNumber + " letras) "); //Update attempts text
        jTextField2.setText(this.secretWordHiddenbr); //Update secret word text
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setText("Cargando...");
        jTextField1.setToolTipText("");
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.setText("Cargando...");
        jTextField2.setFocusable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Letra");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setText("Letras introducidas:  Ninguna.");
        jTextField4.setToolTipText("");

        jButton1.setText("¡Prueba suerte!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextField5.setText("¿Sabes la palabra?");
        jTextField5.setToolTipText("");

        jLabel3.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.attempts += 1;
        if(this.attempts <= this.totalAttempts)
        {
            jTextField1.setText("Intento " + this.attempts + " de " + this.totalAttempts + " (" + lettersNumber + " letras) "); //Update attempts text
            String newHiddenWord = "";
            if(jTextField3.getText().equals(""))
            {
                jTextField3.setText("Letra");
            }
            char inputLetter = jTextField3.getText().charAt(0);
            if(lettersPut.indexOf(inputLetter) == -1)
            {
                lettersPut += inputLetter;
            }
            for(int i = 0; i < this.secretWordbr.length(); i++)
            {
                if(Character.toLowerCase(inputLetter) == Character.toLowerCase(this.secretWordbr.charAt(i)) && this.secretWordHiddenbr.charAt(i) == '_')
                {
                    newHiddenWord += inputLetter;
                }
                else if (this.secretWordHiddenbr.charAt(i) != '_')
                {
                    newHiddenWord += this.secretWordHiddenbr.charAt(i);
                }
                else
                {
                    newHiddenWord += '_';
                }
            }
            if(newHiddenWord.toLowerCase().equals(this.secretWordbr.toLowerCase()))
            {
                this.setVisible(false);
                new v7Won(this.secretWordbr).setVisible(true); // GAME WON!!
            }
            if(!jTextField5.getText().equals("¿Sabes la palabra?"))
            {
                if(!jTextField5.getText().toLowerCase().equals(this.secretWordbr.toLowerCase()))
                {
                    if(debug)
                    {
                        System.out.println("Palabra incorrecta: " + jTextField5.getText());
                    }
                    jTextField5.setText("¡Palabra incorrecta!");
                }
                else
                {
                    this.setVisible(false);
                    new v7Won(this.secretWordbr).setVisible(true); // GAME WON!!
                }
            }
            this.secretWordHiddenbr = newHiddenWord;
            if(debug)
            {
                System.out.println("Letra introducida: " + inputLetter);
                System.out.println("Palabra oculta: " + this.secretWordbr);
                System.out.println("Palabra oculta hidden: " + this.secretWordHiddenbr);
            }
            jTextField3.setText("");
            jTextField4.setText("Letras introducidas: " + this.lettersPut);
            jTextField2.setText(newHiddenWord); //Update secret word text
        }
        else
        {
            this.setVisible(false);
            new v6Lost(this.secretWordbr).setVisible(true); // GAME LOST!!
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v5StartGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
